# Generated by Django 5.1.6 on 2025-03-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=255)),
                ('industry_other', models.CharField(blank=True, max_length=255, null=True)),
                ('target_audience', models.CharField(max_length=255)),
                ('technology', models.JSONField()),
                ('sub_technology', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('web_frontend', models.JSONField(blank=True, null=True)),
                ('web_backend', models.JSONField(blank=True, null=True)),
                ('web_hosting', models.JSONField(blank=True, null=True)),
                ('web_database', models.JSONField(blank=True, null=True)),
                ('security_features', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_suggestion', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
